'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Black_Han_Sans } from 'next/font/google'
import { RecoilRoot } from 'recoil'

const inter = Black_Han_Sans({ subsets: ['latin'], weight: ['400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <RecoilRoot>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </RecoilRoot>
  )
}
